# mandatory values (2) , optional values

- name: Frontend App
  hosts: all
  tasks:
    - ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy Expense Nginx Configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Clean the old Content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent  

    - name: Create App Dir
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory 

    - name: Download the frontend content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip 
        dest: /usr/share/nginx/html   
        remote_src: yes    

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx    
        enabled: true 

    